### ISSUE TITLE
Update algoliasearch to v4

### ISSUE THREAD

**Issue by prichey** [algolia/gatsby-plugin-algolia#102]
Currently the plugin depends on `algoliasearch@^3.24.5`, which hasn't been updated in 3 years (since the initial commit, I think?). It'd be great to update to v4 to be consistent with online documentation. I may be able to work on a PR for this, pending other work in progress

**Comment by Haroenv** [comment]
algoliasearch@3 is no longer recommended, but it's not 3 years old :p version 4 has only been released this February.

I hadn't updated yet because I wasn't sure whether the behaviour of .wait and .waitTask is really the same, but that part of the code is quite different now, so no longer an issue.

browse is also quite different, but that should be a small focused change

**Comment by prichey** [comment]
Ah, I was just referring to the specific version in the repo. No offense intended! 😊

<img width="346" alt="Screen Shot 2020-10-14 at 1 29 03 PM" src="https://user-images.githubusercontent.com/1418487/96024149-5bb17c00-0e21-11eb-84e1-272b64bcaa39.png">

**Comment by marcelovicentegc** [comment]
Hi, @prichey! You might want to take a look at this PR: https://github.com/algolia/gatsby-plugin-algolia/pull/135

**Comment by Haroenv** [comment]
Thanks for your PR @marcelovicentegc !

**Comment by marcelovicentegc** [comment]
Hey, all! It occurs to me that this issue can be closed since https://github.com/algolia/gatsby-plugin-algolia/pull/135 was merged 😉
