### ISSUE TITLE
Adding new data to existing records is ignored

### ISSUE THREAD

**Issue by andrewsjohnson** [algolia/gatsby-plugin-algolia#181]
Hi! I've run into a case where we need to add new data — as in new fields that didn't previously get pushed to algolia but *did* always exist in the source gatsby was pulling from — but because those entries haven't been "updated," the only way I can get algolia and this plugin to understand that there's new data and actually reflect that new data in the index is to clear the entire index and rebuild it.

Is there some sort of override that allows us to overwrite the data for each entry in the index, like a force update? As it is, clearing the index and hoping our build is successful feels real risky.

**Comment by Haroenv** [comment]
I haven't come across that feature request yet, I think the easiest would be to locally index it once to a different index, then use `moveIndex` to replace your production index with the locally created index with all information in it. Then from that point on everything should work as expected.

We're relying on contentDigest of the nodes, so that wouldn't have changed in your case, unless you change the nodes as well in Gatsby, which could be an alternative option.

**Comment by Haroenv** [comment]
What you could also do is in the transformer, add some `&version=123` to the contentDigest, which then would imply to the rest of indexing that all objects have updated, and thus will index as you'd expect
