### ISSUE TITLE
Partial Index Update

### ISSUE THREAD

**Issue by Blackglade** [algolia/gatsby-plugin-algolia#34]
Anyway to implement this: https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/

or this: https://www.algolia.com/doc/api-reference/api-methods/save-objects/

so that the entire Index isn't updated at build and only the changed values in the index are updated?

**Comment by Haroenv** [comment]
One thing to note is that partial update objects will still cost the same amount of operations, since it would be called even if there's nothing to update. 

There's an experiment by someone in the community in #27 you can try out with the plugin gatsby-pluign-algolia-search they published to try it out.

**Comment by fraserisland** [comment]
@Haroenv I'm a bit confused on how this would cost the same amount of operations, wouldn't allowing partial updates only index the updated items which for example could mean only 1 index operation vs 3000(or whatever your index size is)?

**Comment by Haroenv** [comment]
Unfortunately for this use case, a partial update which didn't cause any change still counts as an operation. The correct way to solve this for operations is _not_ doing the API calls, as done in #27

**Comment by Haroenv** [comment]
This has been implemented as `enablePartialUpdates: true` in 0.8.0
